magic_fails = ("1. Spell Burn. Roll 1d4 magic damage against yourself.", 
'2. Spell Backfire. Roll a Dexterity Saving Throw (DC 13) or be blown back 5 ft. and knocked prone.', 
'3. Spell Backfire. Roll a Dexterity Saving Throw (DC 13) or be blown back 5 ft. and knocked prone.', 
'4. Spell Backfire. Roll a Dexterity Saving Throw (DC 13) or be blown back 5 ft. and knocked prone.', 
'5. Spell Backfire. Roll a Dexterity Saving Throw (DC 13) or be blown back 5 ft. and knocked prone.', 
'6. Spell Backfire. Roll a Dexterity Saving Throw (DC 13) or be blown back 5 ft. and knocked prone.', 
'7. Spell Backfire. Roll a Dexterity Saving Throw (DC 13) or be blown back 5 ft. and knocked prone.', 
'8. Spell Backfire. Roll a Dexterity Saving Throw (DC 13) or be blown back 5 ft. and knocked prone.', 
'9. Spell Backfire. Roll a Dexterity Saving Throw (DC 13) or be blown back 5 ft. and knocked prone.', 
'10. Spell Backfire. Roll a Dexterity Saving Throw (DC 13) or be blown back 5 ft. and knocked prone.', 
'11. Magic Drain. Make a Constitution Saving Throw (DC 13). On a fail you have disadvantage on your next attack.', 
'12. Magic Drain. Make a Constitution Saving Throw (DC 13). On a fail you have disadvantage on your next attack.', 
'13. Magic Drain. Make a Constitution Saving Throw (DC 13). On a fail you have disadvantage on your next attack.', 
'14. Magic Drain. Make a Constitution Saving Throw (DC 13). On a fail you have disadvantage on your next attack.', 
'15. Magic Drain. Make a Constitution Saving Throw (DC 13). On a fail you have disadvantage on your next attack.', 
'16. Magic Drain. Make a Constitution Saving Throw (DC 13). On a fail you have disadvantage on your next attack.', 
'17. Magic Drain. Make a Constitution Saving Throw (DC 13). On a fail you have disadvantage on your next attack.', 
'18. Magic Drain. Make a Constitution Saving Throw (DC 13). On a fail you have disadvantage on your next attack.', 
'19. Magic Drain. Make a Constitution Saving Throw (DC 13). On a fail you have disadvantage on your next attack.', 
"20. Nothing Happens. No one noticed. You totally missed on purpose. It's all a part of the plan.")

magic_h_fails = ("1. Spell Burn. You inflict your spell's damage against yourself.", 
'2. Uncontrolled Casting. Randomise all combatants within 15 ft and roll to see who you attack. Roll a new attack against that target.', 
'3. Uncontrolled Casting. Randomise all combatants within 15 ft and roll to see who you attack. Roll a new attack against that target.', 
'4. Wild Magic. Roll on the Wild Magic Table.', 
'5. Spell Backfire. Roll a Dexterity Saving Throw (DC 13) or be blown back 5 ft. and knocked prone.', 
'6. Spell Backfire. Roll a Dexterity Saving Throw (DC 13) or be blown back 5 ft. and knocked prone.', 
'7. Spell Backfire. Roll a Dexterity Saving Throw (DC 13) or be blown back 5 ft. and knocked prone.', 
'8. Spell Backfire. Roll a Dexterity Saving Throw (DC 13) or be blown back 5 ft. and knocked prone.', 
'9. Spell Backfire. Roll a Dexterity Saving Throw (DC 13) or be blown back 5 ft. and knocked prone.', 
'10. Spell Backfire. Roll a Dexterity Saving Throw (DC 13) or be blown back 5 ft. and knocked prone.', 
'11. Concentration Break. Make a Constitution Saving Throw (DC 13) or lose concentration on any existing spells.', 
'12. Concentration Break. Make a Constitution Saving Throw (DC 13) or lose concentration on any existing spells.', 
'13. Concentration Break. Make a Constitution Saving Throw (DC 13) or lose concentration on any existing spells.', 
'14. Concentration Break. Make a Constitution Saving Throw (DC 13) or lose concentration on any existing spells.', 
'15. Magic Drain. Make a Constitution Saving Throw (DC 13). On a fail you have disadvantage on your next attack.', 
'16. Magic Drain. Make a Constitution Saving Throw (DC 13). On a fail you have disadvantage on your next attack.', 
'17. Magic Drain. Make a Constitution Saving Throw (DC 13). On a fail you have disadvantage on your next attack.', 
'18. Magic Drain. Make a Constitution Saving Throw (DC 13). On a fail you have disadvantage on your next attack.', 
'19. Magic Drain. Make a Constitution Saving Throw (DC 13). On a fail you have disadvantage on your next attack.', 
"20. Nothing Happens. No one noticed. You totally missed on purpose. It's all a part of the plan.")

melee_fails = ('1. You hit yourself. Somehow you accidentally struck yourself. Roll 1d4 damage of the same type as your weapon against yourself.', 
'2. Disarmed. Roll an Athletics check (DC 13) or drop your weapon.', 
'3. Disarmed. Roll an Athletics check (DC 13) or drop your weapon.', 
'4. Disarmed. Roll an Athletics check (DC 13) or drop your weapon.', 
'5. Disarmed. Roll an Athletics check (DC 13) or drop your weapon.', 
'6. Disarmed. Roll an Athletics check (DC 13) or drop your weapon.', 
'7. Disarmed. Roll an Athletics check (DC 13) or drop your weapon.', 
'8. Disarmed. Roll an Athletics check (DC 13) or drop your weapon.', 
'9. Disarmed. Roll an Athletics check (DC 13) or drop your weapon.', 
'10. Stumble. Roll a Acrobatics check (DC 13) or fall prone.', 
'11. Stumble. Roll a Acrobatics check (DC 13) or fall prone.', 
'12. Stumble. Roll a Acrobatics check (DC 13) or fall prone.', 
'13. Stumble. Roll a Acrobatics check (DC 13) or fall prone.', 
'14. Stumble. Roll a Acrobatics check (DC 13) or fall prone.', 
'15. Stumble. Roll a Acrobatics check (DC 13) or fall prone.', 
'16. Stumble. Roll a Acrobatics check (DC 13) or fall prone.', 
'17. Embarrassed. Make a Constitution Saving Throw (DC 13). On a fail you have disadvantage on your next attack.', 
'18. Embarrassed. Make a Constitution Saving Throw (DC 13). On a fail you have disadvantage on your next attack.', 
'19. Embarrassed. Make a Constitution Saving Throw (DC 13). On a fail you have disadvantage on your next attack.', 
"20. Nothing Happens. No one noticed. You totally missed on purpose. It's all a part of the plan.")

melee_h_fails = ('1. Your weapon has broken! (For Magical Weapons, roll an additional d20. it breaks on a 1.)', 
'2. Your weapon has broken! (For Magical Weapons, roll an additional d20. it breaks on a 1.)', 
'3. You threw your weapon! Roll an Athletics check (DC 15), or your weapon flies d12 feet away from you.', 
'4. You threw your weapon! Roll an Athletics check (DC 15), or your weapon flies d12 feet away from you.', 
'5. Overextended! You swung too hard and pulled something. Your opponent has advantage against you on their next turn.', 
'6. Overextended! You swung too hard and pulled something. Your opponent has advantage against you on their next turn.', 
'7. Stuck Weapon. Your weapon gets stuck in the ground. Roll a Strength check to see if you can free it using a bonus action. The DC is 8 + your strength modifier.', 
'8. Wrong Target! Randomise all combatants within 5 ft and roll to see who you attack. Roll a new attack against that target. (Discount sneak attack damage for Rogues).', 
'9. You manage to hit yourself with your own weapon. Doh! Roll normal damage and half it.', 
'10. Tripped up. You fall prone. Roll a Dexterity check (DC 15) or fall prone. Your turn has ended and melee attacks have advantage against you ', 
'11. Tripped up. You fall prone. Roll a Dexterity check (DC 15) or fall prone. Your turn has ended and melee attacks have advantage against you.', 
'12. Tripped up. You fall prone. Roll a Dexterity check (DC 15) or fall prone. Your turn has ended and melee attacks have advantage against you.', 
'13. Tripped up. You fall prone. Roll a Dexterity check (DC 15) or fall prone. Your turn has ended and melee attacks have advantage against you.', 
'14. Tripped up. You fall prone. Roll a Dexterity check (DC 15) or fall prone. Your turn has ended and melee attacks have advantage against you.', 
'15. Pulled Muscle (Arms). Roll a Constitution Saving Throw DC 15 or the strain of your attack causes you to pull a muscle in your upper body. You have disadvantage in attack rolls and ability checks requiring upper body strength until you have completed three long rests, or received magical healing.', 
'16. Pulled Muscle (Legs). Roll a Constitution Saving Throw DC 15 or the strain of combat causes you to pull a muscle in your leg. Your movement is halved, and you lose your Dex modifier to AC and initiative, and you have disadvantage on any ability checks that require lower body strength, until you have completed three long rests, or received magical healing.', 
'17. Loss of Nerve. Make a Wisdom Saving Throw with a base DC of 10 modified by +2 for every hit dice higher than you your opponent has (or -2 for every hit dice less). On a fail you are frightened. After one turn you can attempt the saving throw again.', 
'18. Loss of Nerve. Make a Wisdom Saving Throw with a base DC of 10 modified by +2 for every hit dice higher than you your opponent has (or -2 for every hit dice less). On a fail you are frightened. After one turn you can attempt the saving throw again.', 
'19. Broken Item. In the hurly burly of combat, something fragile – like a magic potion – you’re carrying breaks. Randomise fragile objects you have in your possession and roll to determine which. (Note, better to do this when the combat is over).', 
'20. A Little Accident. Either through fear, excitement or simply needing to go, you soil yourself. There is like a 75% chance it’s only pee...')

nat_fails = ("1. You hit yourself. Somehow you accidentally struck yourself. Roll 1d4 damage of the same damage type as your attack against yourself.", 
"2. Stumble. Roll a Dexterity check (DC 13) or fall prone.", 
"3. Stumble. Roll a Dexterity check (DC 13) or fall prone.", 
"4. Stumble. Roll a Dexterity check (DC 13) or fall prone.", 
"5. Stumble. Roll a Dexterity check (DC 13) or fall prone.", 
"6. Stumble. Roll a Dexterity check (DC 13) or fall prone.", 
"7. Off Balance. Make a Constitution Saving Throw (DC 13). On a fail you have disadvantage on your next attack.", 
"8. Off Balance. Make a Constitution Saving Throw (DC 13). On a fail you have disadvantage on your next attack.",
"9. Off Balance. Make a Constitution Saving Throw (DC 13). On a fail you have disadvantage on your next attack.",
"10. Nothing Happens. No one noticed. You totally missed on purpose. It's all a part of the plan.")

nat_h_fails = ("1. Ouch! The attacker snaps one or several teeth / claws on its target’s weapon or armour, or nearby surface. They receive 1d3 hp of damage, and furthermore they must subtract the result of the same d3 roll from damage done from this attack from now on. (Ignore for tail attacks).", 
"2. Ouch! The attacker snaps one or several teeth / claws on its target’s weapon or armour, or nearby surface. They receive 1d3 hp of damage, and furthermore they must subtract the result of the same d3 roll from damage done from this attack from now on. (Ignore for tail attacks).", 
"3. Wild Swing. The attacker overextends itself going for the kill. Their intended target gains advantage on their next attack roll.", 
"4. Wild Swing. The attacker overextends itself going for the kill. Their intended target gains advantage on their next attack roll.", 
"5. Wild Swing. The attacker overextends itself going for the kill. Their intended target gains advantage on their next attack roll.", 
"6. Slip Up. The attacker loses its footing. Roll Dexterity / Acrobatics check (DC 15) or fall prone. Their turn has ended and melee attacks have advantage on you (see p.292 of PH for conditions of being prone). Creatures with more than two legs are immune to this effect.", 
"7. Slip Up. The attacker loses its footing. Roll Dexterity / Acrobatics check (DC 15) or fall prone. Their turn has ended and melee attacks have advantage on you (see p.292 of PH for conditions of being prone). Creatures with more than two legs are immune to this effect.", 
"8. Loss of Nerve. The attacker is scared. They must make a Wisdom Saving Throw with a base DC of 10 modified by +2 for every hit dice higher the target of the attack has vs. the attacker (or -2 for every hit dice less). On a fail they are frightened (see p.292 of Player’s Handbook). After one turn they can attempt the saving throw again. Creatures that inspire fear are immune to this effect (unless their target also inspires fear).",
"9. Loss of Nerve. The attacker is scared. They must make a Wisdom Saving Throw with a base DC of 10 modified by +2 for every hit dice higher the target of the attack has vs. the attacker (or -2 for every hit dice less). On a fail they are frightened (see p.292 of Player’s Handbook). After one turn they can attempt the saving throw again. Creatures that inspire fear are immune to this effect (unless their target also inspires fear).",
"10. Loss of Nerve. The attacker is scared. They must make a Wisdom Saving Throw with a base DC of 10 modified by +2 for every hit dice higher the target of the attack has vs. the attacker (or -2 for every hit dice less). On a fail they are frightened (see p.292 of Player’s Handbook). After one turn they can attempt the saving throw again. Creatures that inspire fear are immune to this effect (unless their target also inspires fear).")

range_fails = ("1. String Snap. Somehow you accidentally snapped your hand. Roll 1d4 slashing damage against yourself.", 
"2. Recoil! Roll an Acrobatics check (DC 13) or fall prone.",
"3. Recoil! Roll an Acrobatics check (DC 13) or fall prone.", 
"4. Recoil! Roll an Acrobatics check (DC 13) or fall prone.", 
"5. Recoil! Roll an Acrobatics check (DC 13) or fall prone.", 
"6. Recoil! Roll an Acrobatics check (DC 13) or fall prone.", 
"7. Recoil! Roll an Acrobatics check (DC 13) or fall prone.",  
"8. Recoil! Roll an Acrobatics check (DC 13) or fall prone.", 
"9. Recoil! Roll an Acrobatics check (DC 13) or fall prone.",
"10. Recoil! Roll an Acrobatics check (DC 13) or fall prone.", 
"11. Dropped Ammo. Roll a Dexterity check (DC 13) or drop your ammo.", 
"12. Dropped Ammo. Roll a Dexterity check (DC 13) or drop your ammo.",
"13. Dropped Ammo. Roll a Dexterity check (DC 13) or drop your ammo.", 
"14. Dropped Ammo. Roll a Dexterity check (DC 13) or drop your ammo.", 
"15. Dropped Ammo. Roll a Dexterity check (DC 13) or drop your ammo.", 
"16. Dropped Ammo. Roll a Dexterity check (DC 13) or drop your ammo.", 
"17. Embarrassed. Make a Constitution Saving Throw (DC 13). On a fail you have disadvantage on your next attack.",
"18. Embarrassed. Make a Constitution Saving Throw (DC 13). On a fail you have disadvantage on your next attack.", 
"19. Embarrassed. Make a Constitution Saving Throw (DC 13). On a fail you have disadvantage on your next attack.", 
"20. Nothing Happens. No one noticed. You totally missed on purpose. It's all a part of the plan.")

range_h_fails = ("1. Weapon Break. Your bow shaft or a mechanism in your crossbow breaks and is now useless. (For magical weapons roll an additional d10, on a 1 they break).", 
"2. Weapon Break. Your bow shaft or a mechanism in your crossbow breaks and is now useless. (For magical weapons roll an additional d10, on a 1 they break).",
"3. String Break. Your bowstring snaps. Assuming you have a spare string, it requires 1 minute to replace it.", 
"4. String Break. Your bowstring snaps. Assuming you have a spare string, it requires 1 minute to replace it.", 
"5. String Break. Your bowstring snaps. Assuming you have a spare string, it requires 1 minute to replace it.", 
"6. Loose String. Your string comes loose. You lose this attack. Starting next turn you can make a sleight of hand check DC 15 to fix it. Each attempt takes one turn.", 
"7. Loose String. Your string comes loose. You lose this attack. Starting next turn you can make a sleight of hand check DC 15 to fix it. Each attempt takes one turn.",  "8. Loose String. Your string comes loose. You lose this attack. Starting next turn you can make a sleight of hand check DC 15 to fix it. Each attempt takes one turn.", 
"9. Oops! You hit an unintended random target. Randomise all combatants within 10 feet (for a short range attack, or 30 feet for a long range attack) and roll a second attack roll, if you beat their armour class roll damage as if they were your intended target (discount sneak attack damage for Rogues).",
"10. Oops! You hit an unintended random target. Randomise all combatants within 10 feet (for a short range attack, or 30 feet for a long range attack) and roll a second attack roll, if you beat their armour class roll damage as if they were your intended target (discount sneak attack damage for Rogues).", 
"11. Oops! You hit an unintended random target. Randomise all combatants within 10 feet (for a short range attack, or 30 feet for a long range attack) and roll a second attack roll, if you beat their armour class roll damage as if they were your intended target (discount sneak attack damage for Rogues).", 
"12. Oops! You hit an unintended random target. Randomise all combatants within 10 feet (for a short range attack, or 30 feet for a long range attack) and roll a second attack roll, if you beat their armour class roll damage as if they were your intended target (discount sneak attack damage for Rogues).",
"13. Oops! You hit an unintended random target. Randomise all combatants within 10 feet (for a short range attack, or 30 feet for a long range attack) and roll a second attack roll, if you beat their armour class roll damage as if they were your intended target (discount sneak attack damage for Rogues).", 
"14. Oops! You hit an unintended random target. Randomise all combatants within 10 feet (for a short range attack, or 30 feet for a long range attack) and roll a second attack roll, if you beat their armour class roll damage as if they were your intended target (discount sneak attack damage for Rogues).", 
"15. Oops! You hit an unintended random target. Randomise all combatants within 10 feet (for a short range attack, or 30 feet for a long range attack) and roll a second attack roll, if you beat their armour class roll damage as if they were your intended target (discount sneak attack damage for Rogues).", 
"16. Oops! You hit an unintended random target. Randomise all combatants within 10 feet (for a short range attack, or 30 feet for a long range attack) and roll a second attack roll, if you beat their armour class roll damage as if they were your intended target (discount sneak attack damage for Rogues).", 
"17. Ammo Accident. Your quiver spills (50% strap broken, 50% you tilt it over by accident), and the remainder of your arrows / bolts fall to the floor. If you remain still you can use a bonus action to pick up one a round and still fire using your action. Otherwise you can use an action to pick up 2d8 and put them back in your quiver.",
"18. Ammo Accident. Your quiver spills (50% strap broken, 50% you tilt it over by accident), and the remainder of your arrows / bolts fall to the floor. If you remain still you can use a bonus action to pick up one a round and still fire using your action. Otherwise you can use an action to pick up 2d8 and put them back in your quiver.", 
"19. Pulled Muscle (Upper Body). Roll a Constitution Saving Throw DC 15 or the strain of your attack causes you to pull a muscle in your upper body. You have disadvantage in attack rolls and ability checks requiring upper body strength until you have completed three long rests, or received magical healing.", 
"20. Slip Up. You lose your footing. Roll Dexterity / Acrobatics (DC 15) or fall prone. Your turn has ended and melee attacks have advantage on you (see p.292 of PH for conditions of being prone).")

thrown_fails = ("1. Worst throw ever. You dropped the object on your foot. Roll 1d4 damage of the same damage type as your attack against yourself.", 
"2. Bad throw. Your weapon lands 1d6*5ft away in a direction of your DM's choosing.", 
"3. Bad throw. Your weapon lands 1d6*5ft away in a direction of your DM's choosing.", 
"4. Bad throw. Your weapon lands 1d6*5ft away in a direction of your DM's choosing.", 
"5. Bad throw. Your weapon lands 1d6*5ft away in a direction of your DM's choosing.", 
"6. Over extended! Roll a Dexterity check (DC 13) or fall prone.", 
"7. Over extended! Roll a Dexterity check (DC 13) or fall prone.", 
"8. Over extended! Roll a Dexterity check (DC 13) or fall prone.",
"9. Over extended! Roll a Dexterity check (DC 13) or fall prone.",
"10. Horrible throw. Your weapon lands at your enemies feet.")

thrown_h_fails = ("1. Weapon Break. The impact of your weapon hitting a tree, the ground, a shield etc. causes it to break. It is now useless. (For magical weapons roll an additional d10, on a 1 they break).", 
"2. Pulled Muscle (Arms). Roll a Constitution Saving Throw DC 15 or the strain of your attack causes you to pull a muscle in your upper body. You have disadvantage in attack rolls and ability checks requiring upper body strength until you have completed three long rests, or received magical healing.", 
"3. Slip Up. You lose your footing. Roll Dexterity / Acrobatics (DC 15) or fall prone. Your turn has ended and melee attacks have advantage on you (see p.292 of PH for conditions of being prone).", 
"4. Slip Up. You lose your footing. Roll Dexterity / Acrobatics (DC 15) or fall prone. Your turn has ended and melee attacks have advantage on you (see p.292 of PH for conditions of being prone).", 
"5. Ooops! You hit an unintended random target. Randomise all combatants within 10 feet (for a short range attack, or 30 feet for a long range attack) and roll a second attack roll, if you beat their armour class roll damage as if they were your intended target (discount sneak attack damage for Rogues).",
"6. Ooops! You hit an unintended random target. Randomise all combatants within 10 feet (for a short range attack, or 30 feet for a long range attack) and roll a second attack roll, if you beat their armour class roll damage as if they were your intended target (discount sneak attack damage for Rogues).",
"7. Ooops! You hit an unintended random target. Randomise all combatants within 10 feet (for a short range attack, or 30 feet for a long range attack) and roll a second attack roll, if you beat their armour class roll damage as if they were your intended target (discount sneak attack damage for Rogues).", 
"8. Ooops! You hit an unintended random target. Randomise all combatants within 10 feet (for a short range attack, or 30 feet for a long range attack) and roll a second attack roll, if you beat their armour class roll damage as if they were your intended target (discount sneak attack damage for Rogues).", 
"9. Ooops! You hit an unintended random target. Randomise all combatants within 10 feet (for a short range attack, or 30 feet for a long range attack) and roll a second attack roll, if you beat their armour class roll damage as if they were your intended target (discount sneak attack damage for Rogues).", 
"10. WTF? You launch a comically bad projectile attack nowhere near your intended opponent – it flies into a huge empty space (or at DM’s discretion a distant unintended target) taking your self confidence with it. Roll wisdom saving throw DC 15, or suffer disadvantage to attack rolls until you next score a hit on an opponent.")
